import type { FertilizerProduct } from '../types/fertilizer';

/**
 * Biblioteca de fertilizantes comerciales de referencia. Composición en % elemental
 * (no en óxidos), tomada de grados comerciales típicos. costoPorKg y factorCE son
 * valores de referencia/placeholder: deben ajustarse a precios e insumos reales.
 */
export const FERTILIZER_LIBRARY: FertilizerProduct[] = [
  {
    id: 'nitrato-calcio',
    nombre: 'Nitrato de calcio',
    formulaComercial: 'Ca(NO3)2',
    estadoFisico: 'solido',
    composicionPct: { N: 15.5, Ca: 19.0 },
    solubilidadGL: 1200,
    pureza: 0.99,
    costoPorKg: 12,
    factorCE: 1.3,
    porcentajeNa: 0,
    porcentajeCl: 0,
    categoriaTanque: 'A',
  },
  {
    id: 'nitrato-magnesio',
    nombre: 'Nitrato de magnesio',
    formulaComercial: 'Mg(NO3)2',
    estadoFisico: 'solido',
    composicionPct: { N: 11.0, Mg: 9.7 },
    solubilidadGL: 900,
    pureza: 0.99,
    costoPorKg: 18,
    factorCE: 1.1,
    porcentajeNa: 0,
    porcentajeCl: 0,
    categoriaTanque: 'A',
  },
  {
    id: 'nitrato-potasio',
    nombre: 'Nitrato de potasio',
    formulaComercial: 'KNO3',
    estadoFisico: 'solido',
    composicionPct: { N: 13.0, K: 38.2 },
    solubilidadGL: 316,
    pureza: 0.99,
    costoPorKg: 22,
    factorCE: 1.4,
    porcentajeNa: 0,
    porcentajeCl: 0,
    categoriaTanque: 'A',
  },
  {
    id: 'sulfato-potasio',
    nombre: 'Sulfato de potasio',
    formulaComercial: 'K2SO4',
    estadoFisico: 'solido',
    composicionPct: { K: 41.5, S: 18.0 },
    solubilidadGL: 111,
    pureza: 0.98,
    costoPorKg: 20,
    factorCE: 1.2,
    porcentajeNa: 0,
    porcentajeCl: 0,
    categoriaTanque: 'B',
  },
  {
    id: 'fosfato-monopotasico',
    nombre: 'Fosfato monopotásico (MKP)',
    formulaComercial: 'KH2PO4',
    estadoFisico: 'solido',
    composicionPct: { P: 22.7, K: 28.2 },
    solubilidadGL: 230,
    pureza: 0.99,
    costoPorKg: 35,
    factorCE: 0.7,
    porcentajeNa: 0,
    porcentajeCl: 0,
    categoriaTanque: 'B',
  },
  {
    id: 'fosfato-monoamonico',
    nombre: 'Fosfato monoamónico (MAP)',
    formulaComercial: 'NH4H2PO4',
    estadoFisico: 'solido',
    composicionPct: { N: 12.0, P: 26.6 },
    solubilidadGL: 370,
    pureza: 0.98,
    costoPorKg: 25,
    factorCE: 0.8,
    porcentajeNa: 0,
    porcentajeCl: 0,
    categoriaTanque: 'B',
  },
  {
    id: 'sulfato-magnesio',
    nombre: 'Sulfato de magnesio',
    formulaComercial: 'MgSO4·7H2O',
    estadoFisico: 'solido',
    composicionPct: { Mg: 9.6, S: 13.0 },
    solubilidadGL: 710,
    pureza: 0.99,
    costoPorKg: 10,
    factorCE: 0.9,
    porcentajeNa: 0,
    porcentajeCl: 0,
    categoriaTanque: 'B',
  },
  {
    id: 'urea',
    nombre: 'Urea',
    formulaComercial: 'CO(NH2)2',
    estadoFisico: 'solido',
    composicionPct: { N: 46.0 },
    solubilidadGL: 1080,
    pureza: 0.99,
    costoPorKg: 11,
    factorCE: 0.3,
    porcentajeNa: 0,
    porcentajeCl: 0,
    categoriaTanque: 'flexible',
  },
  {
    id: 'acido-fosforico',
    nombre: 'Ácido fosfórico',
    formulaComercial: 'H3PO4 (75%)',
    estadoFisico: 'liquido',
    composicionPct: { P: 23.6 },
    densidadKgL: 1.58,
    pureza: 0.75,
    costoPorKg: 28,
    factorCE: 0.5,
    porcentajeNa: 0,
    porcentajeCl: 0,
    categoriaTanque: 'C',
  },
  {
    id: 'acido-nitrico',
    nombre: 'Ácido nítrico',
    formulaComercial: 'HNO3 (56%)',
    estadoFisico: 'liquido',
    composicionPct: { N: 12.3 },
    densidadKgL: 1.35,
    pureza: 0.56,
    costoPorKg: 15,
    factorCE: 0.4,
    porcentajeNa: 0,
    porcentajeCl: 0,
    categoriaTanque: 'C',
  },
  {
    id: 'acido-sulfurico',
    nombre: 'Ácido sulfúrico',
    formulaComercial: 'H2SO4 (98%)',
    estadoFisico: 'liquido',
    composicionPct: { S: 31.0 },
    densidadKgL: 1.84,
    pureza: 0.98,
    costoPorKg: 9,
    factorCE: 0.4,
    porcentajeNa: 0,
    porcentajeCl: 0,
    categoriaTanque: 'C',
  },
  {
    id: 'quelato-hierro',
    nombre: 'Quelato de hierro (Fe-EDDHA)',
    estadoFisico: 'solido',
    composicionPct: { Fe: 6.0 },
    solubilidadGL: 100,
    pureza: 0.95,
    costoPorKg: 90,
    factorCE: 0.1,
    porcentajeNa: 0,
    porcentajeCl: 0,
    categoriaTanque: 'A',
  },
  {
    id: 'mezcla-micronutrientes',
    nombre: 'Mezcla de micronutrientes',
    estadoFisico: 'solido',
    composicionPct: { Fe: 7.0, Mn: 2.0, Zn: 1.0, Cu: 0.5, B: 0.5, Mo: 0.05 },
    solubilidadGL: 200,
    pureza: 0.95,
    costoPorKg: 60,
    factorCE: 0.2,
    porcentajeNa: 0,
    porcentajeCl: 0,
    categoriaTanque: 'B',
  },
  {
    id: 'acidos-humicos-fulvicos',
    nombre: 'Ácidos húmicos y fúlvicos',
    estadoFisico: 'liquido',
    composicionPct: {},
    densidadKgL: 1.1,
    pureza: 0.15,
    costoPorKg: 40,
    factorCE: 0.1,
    porcentajeNa: 0,
    porcentajeCl: 0,
    categoriaTanque: 'C',
  },
  {
    id: 'producto-chaman-bioestimulante',
    nombre: 'Producto Chamán (bioestimulante)',
    estadoFisico: 'liquido',
    composicionPct: {},
    densidadKgL: 1.05,
    pureza: 1,
    costoPorKg: 50,
    factorCE: 0.05,
    porcentajeNa: 0,
    porcentajeCl: 0,
    categoriaTanque: 'C',
  },
];

export function getFertilizerById(id: string): FertilizerProduct {
  const producto = FERTILIZER_LIBRARY.find((f) => f.id === id);
  if (!producto) throw new Error(`Fertilizante no encontrado en la biblioteca: ${id}`);
  return producto;
}
